server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/pacientes
    username: app_user
    password: app123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db_migration
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/hospital

springdoc:
  swagger-ui:
    path: /swagger-ui.html